services:
  valex-db:
    environment:
      POSTGRES_DB: valex_test

  valex-api:
    container_name: valex-api-test
    command: npm test
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
    env_file:
      - .env
    environment:
      POSTGRES_DB: valex_test
      NODE_ENV: test
